/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.8.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package za.co.protogen.core.domain.api;

import za.co.protogen.core.domain.models.delegate.AddCarApiDelegate;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-11-07T20:54:30.516515700+02:00[Africa/Johannesburg]", comments = "Generator version: 7.8.0")
@Validated
@Tag(name = "cars", description = "the cars API")
public interface AddCarApi {

    default AddCarApiDelegate getDelegate() {
        return new AddCarApiDelegate() {};
    }

    /**
     * POST /add_car/{vin}/{price}/{year} : Create new car
     *
     * @param vin The vin(Vehicle Identification Number) of the car to retrieve (required)
     * @param price Price of the car
     * @param year How old the vehicle is
     * @return Successful responds with message and repository current size (status code 200)
     */
    @Operation(
        operationId = "createCar",
        summary = "Create new car",
        tags = { "cars", "new", "add" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful responds with message and repository current size", content = {
                @Content(mediaType = "text/html", schema = @Schema(implementation = String.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/add_car/{vin}/{price}/{year}",
        produces = { "text/html" }
    )
    
    default ResponseEntity<String> createCar(
        @Parameter(name = "vin", description = "The vin(Vehicle Identification Number) of the car to retrieve", required = true, in = ParameterIn.PATH) @PathVariable("vin") String vin ,@Parameter(name = "price", description = "Price of the car", required = true, in = ParameterIn.PATH) @PathVariable("price") int price,
        @Parameter(name = "year", description = "How old the vehicle is", required = true, in = ParameterIn.PATH) @PathVariable("year") int year


    ) {
        return getDelegate().createCar(vin,price,year);
    }

}
