/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.8.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package za.co.protogen.core.domain.api;

import za.co.protogen.core.domain.models.delegate.GetCarColorApiDelegate;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import javax.validation.constraints.*;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-11-07T20:54:30.516515700+02:00[Africa/Johannesburg]", comments = "Generator version: 7.8.0")
@Validated
@Tag(name = "car", description = "the car API")
public interface GetCarColorApi {

    default GetCarColorApiDelegate getDelegate() {
        return new GetCarColorApiDelegate() {};
    }

    /**
     * GET /getCar_color : Find and Return car using color
     *
     * @param color Car color used to retrieve car (required)
     * @return Successful Responds. Return List of Cars matching color criteria (status code 200)
     *         or No Car matches color criteria or Empty Repository (status code 404)
     */
    @Operation(
        operationId = "getByColor",
        summary = "Find and Return car using color",
        tags = { "car", "find", "color", "return" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful Responds. Return List of Cars matching color criteria", content = {
                @Content(mediaType = "text/html", schema = @Schema(implementation = String.class))
            }),
            @ApiResponse(responseCode = "404", description = "No Car matches color criteria or Empty Repository", content = {
                @Content(mediaType = "text/html", schema = @Schema(implementation = String.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/getCar_color",
        produces = { "text/html" }
    )
    
    default ResponseEntity<String> getByColor(
        @NotNull @Parameter(name = "color", description = "Car color used to retrieve car", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "color", required = true) String color
    ) {
        return getDelegate().getByColor(color);
    }

}
