/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.8.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package za.co.protogen.core.domain.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import za.co.protogen.core.domain.models.delegate.GetAllUsersApiDelegate;

import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-11-10T10:21:23.805578500+02:00[Africa/Johannesburg]", comments = "Generator version: 7.8.0")
@Validated
@Tag(name = "user", description = "the user API")
public interface GetAllUsersApi {

    default GetAllUsersApiDelegate getDelegate() {
        return new GetAllUsersApiDelegate() {};
    }

    /**
     * GET /getAllUsers : Return all users
     *
     * @return Successful. Responds with message and List of users (status code 200)
     *         or Repository empty (status code 404)
     */
    @Operation(
        operationId = "getAllUsers",
        summary = "Return all users",
        tags = { "user", "All", "users" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful. Responds with message and List of users", content = {
                @Content(mediaType = "text/html", schema = @Schema(implementation = String.class))
            }),
            @ApiResponse(responseCode = "404", description = "Repository empty", content = {
                @Content(mediaType = "text/html", schema = @Schema(implementation = String.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/getAllUsers",
        produces = { "text/html" }
    )
    
    default ResponseEntity<String> getAllUsers(
        
    ) {
        return getDelegate().getAllUsers();
    }

}
