/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.8.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package za.co.protogen.controller.models.openapi.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-11-05T20:49:04.739846900+02:00[Africa/Johannesburg]", comments = "Generator version: 7.8.0")
@Validated
@Tag(name = "car", description = "the car API")
public interface GetAllCarsApi {

    default GetAllCarsApiDelegate getDelegate() {
        return new GetAllCarsApiDelegate() {};
    }

    /**
     * GET /getAllCars : Return all cars
     *
     * @return Successful. Responds with List of cars (status code 200)
     *         or Repository empty (status code 404)
     */
    @Operation(
        operationId = "getAll",
        summary = "Return all cars",
        tags = { "car", "All" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful. Responds with List of cars", content = {
                @Content(mediaType = "text/html", schema = @Schema(implementation = String.class))
            }),
            @ApiResponse(responseCode = "404", description = "Repository empty", content = {
                @Content(mediaType = "text/html", schema = @Schema(implementation = String.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/getAllCars",
        produces = { "text/html" }
    )
    
    default ResponseEntity<String> getAll(
        
    ) {
        return getDelegate().getAll();
    }

}
