/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.8.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package za.co.protogen.controller.models.openapi.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;
import javax.validation.constraints.*;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-11-05T20:49:04.739846900+02:00[Africa/Johannesburg]", comments = "Generator version: 7.8.0")
@Validated
@Tag(name = "car", description = "the car API")
public interface GetCarYearApi {

    default GetCarYearApiDelegate getDelegate() {
        return new GetCarYearApiDelegate() {};
    }

    /**
     * GET /getCar_year : Find and Return car using year
     *
     * @param year Car year used to retrieve car (required)
     * @return Successful Responds. Return List of Cars matching year criteria (status code 200)
     *         or No Car matches year criteria or Empty Repository (status code 404)
     */
    @Operation(
        operationId = "getByYear",
        summary = "Find and Return car using year",
        tags = { "car", "find", "year", "return" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful Responds. Return List of Cars matching year criteria", content = {
                @Content(mediaType = "text/html", schema = @Schema(implementation = String.class))
            }),
            @ApiResponse(responseCode = "404", description = "No Car matches year criteria or Empty Repository", content = {
                @Content(mediaType = "text/html", schema = @Schema(implementation = String.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/getCar_year",
        produces = { "text/html" }
    )
    
    default ResponseEntity<String> getByYear(
        @NotNull @Parameter(name = "year", description = "Car year used to retrieve car", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "year", required = true) Integer year
    ) {
        return getDelegate().getByYear(year);
    }

}
